name: "Hello Actions"
description: "Greet someone"
author: "shreyas.sreenivasa@gmail.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  iamge: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
